export const FETCH_CART = 'FETCH_CART';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';


export const ADD_CART = 'ADD_CART';
export const ADD_CART_SUCCESS= 'ADD_CART_SUCCESS'

export const DELETE_CART = 'DELETE_CART';
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS';

export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';


export const  CART_URL = 'https://603636dac3d42700172e6655.mockapi.io/thanh/cart'

export const FETCH_LIST_CHECKOUT = 'FETCH_LIST_CHECKOUT';
export const  FETCH_LIST_CHECKOUT_SUCCESS = 'FETCH_LIST_CHECKOUT_SUCCESS';

export const SET_LIST_CHECKOUT  =  'SET_LIST_CHECKOUT';
export const SET_LIST_CHECKOUT_SUCCESS = 'SET_LIST_CHECKOUT_SUCCESS';

export const SET_LIST_WAITING = 'SET_LIST_WAITING';
export const SET_LIST_WAITING_SUCCESS = 'SET_LIST_WAITING_SUCCESS';
export const FETCH_LIST_WAITING = 'FETCH_LIST_WAITING';
export const FETCH_LIST_WAITING_SUCCESS = 'FETCH_LIST_WAITING_SUCCESS';

export const SET_LIST_DANHAN = 'SET_LIST_DANHAN';
export const SET_LIST_DANHAN_SUCCESS = 'SET_LIST_DANHAN_SUCCESS';
export const FETCH_LIST_DANHAN = 'SET_LIST_DANHAN';
export const FETCH_LIST_DANHAN_SUCCESS = 'SET_LIST_DANHAN_SUCCESS';

export const ADD_LIST_DANHAN = 'ADD_LIST_DANHAN';
export const ADD_LIST_DANHAN_SUCCESS = 'ADD_LIST_DANHAN_SUCCESS';

export const ADD_LIST_CANCEL = 'ADD_LIST_CANCEL';
export const ADD_LIST_CANCEL_SUCCESS = 'ADD_LIST_CANCEL_SUCCESS';
export const FETCH_LIST_CANCEL = 'FETCH_LIST_CANCEL';
export const FETCH_LIST_CANCEL_SUCCESS = 'FETCH_LIST_CANCEL_SUCCESS';
export const DELETE_PRODUCT_CANCEL = 'DELETE_PRODUCT_CANCEL';

