export const ADD_LIST_COMMENT = 'ADD_LIST_COMMENT';
export const ADD_LIST_COMMENT_SUCCESS = 'ADD_LIST_COMMENT_SUCCESS';

export const FETCH_LIST_COMMENT = 'FETCH_LIST_COMMENT';
export const FETCH_LIST_COMMENT_SUCCESS = 'FETCH_LIST_COMMENT_SUCCESS';