export const FETCH_LIST = 'FETCH_LIST';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAIL = 'FETCH_LIST_FAIL';

export const ADD_PRODUCT='ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS='ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAIL='ADD_PRODUCT_FAIL';
export const EDIT_TASK = 'EDIT_TASK'


export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCSESS';

export const FETCH_TYPE_PRODUCT = 'FETCH_TYPE_PRODUCT';
export const FETCH_TYPE_PRODUCT_SUCCESS = 'FETCH_TYPE_PRODUCT_SUCCESS';

export const FETCH_LIST_NOIBAT = 'FETCH_LIST_NOIBAT';
export const FETCH_LIST_NOIBAT_SUCCESS = 'FETCH_LIST_NOIBAT_SUCESS';

export const FETCH_LIST_SALE  = 'FETCH_LIST_SALE';
export const FETCH_LIST_SALE_SUCCESS = 'FETCH_LIST_SALE_SUCCESS';